"""Markdown renderer — single functional file, terminal + IDE friendly."""
from __future__ import annotations

from render.view import FindingView, ProjectSummary, ReportData


_SEVERITY_LABELS = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
}


def render_markdown(data: ReportData) -> str:
    parts: list[str] = []
    parts.append("# Claude Code Harness Audit")
    parts.append("")
    parts.append(
        f"_Generated: {data.generated_at} · "
        f"{data.totals['projects']} projects · "
        f"{data.totals['findings']} findings_"
    )
    parts.append("")
    parts.append(f"Project roots scanned: {', '.join(f'`{r}`' for r in data.configured_roots) or '_(none)_'}")
    parts.append("")

    parts.extend(_render_summary(data))
    parts.append("")
    parts.extend(_render_top_reco(data))
    parts.append("")
    parts.extend(_render_all_findings(data))
    parts.append("")
    parts.extend(_render_projects(data))
    parts.append("")
    parts.append("---")
    parts.append("_Generated by harness-audit · single-file report · safe to share._")
    parts.append("")
    return "\n".join(parts)


def _render_summary(data: ReportData) -> list[str]:
    t = data.totals
    return [
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Projects scanned | {t['projects']} |",
        f"| Instrumented | {t['instrumented']} |",
        f"| Uninstrumented | {t['uninstrumented']} |",
        f"| Findings (total) | {t['findings']} |",
        f"| Critical | {t['critical']} |",
        f"| High | {t['high']} |",
        f"| Medium | {t['medium']} |",
        f"| Low | {t['low']} |",
    ]


def _render_top_reco(data: ReportData) -> list[str]:
    if not data.top_recommendations:
        return ["## Top recommendations", "", "_No findings — nothing to recommend._"]
    out = ["## Top recommendations", ""]
    for i, f in enumerate(data.top_recommendations, 1):
        out.append(
            f"{i}. **[{_SEVERITY_LABELS[f.severity]}]** {f.title} — {f.suggested_fix}"
        )
    return out


def _render_all_findings(data: ReportData) -> list[str]:
    if not data.findings:
        return ["## All findings", "", "_No findings._"]
    out = ["## All findings", ""]
    for f in data.findings:
        out.extend(_render_finding(f))
        out.append("")
    return out


def _render_finding(f: FindingView) -> list[str]:
    scope_lines = ", ".join(f"`{p}`" for p in f.scope_paths)
    return [
        f"### [{_SEVERITY_LABELS[f.severity]}] {f.id} — {f.title}",
        "",
        f"- **Scope ({len(f.scope_paths)}):** {scope_lines}",
        f"- **Evidence:** {f.evidence}",
        f"- **Why it matters:** {f.rationale}",
        f"- **Suggested fix:** {f.suggested_fix}",
    ]


def _render_projects(data: ReportData) -> list[str]:
    out = ["## Per-project drilldown", ""]
    for p in data.projects:
        out.extend(_render_project(p))
        out.append("")
    return out


def _render_project(p: ProjectSummary) -> list[str]:
    label = "Global" if p.is_global else p.name
    status = "instrumented" if p.is_instrumented else "uninstrumented"
    header = f"### {label} · `{p.display_path}`"
    summary = (
        f"_{len(p.artifacts)} artifacts · {len(p.findings)} findings · {status}"
        + (f" · worst: {_SEVERITY_LABELS[p.worst_severity]}_" if p.worst_severity else "_")
    )
    body: list[str] = [header, "", summary, ""]

    if p.artifacts:
        body.append("**Artifacts:**")
        body.append("")
        for kind, path in p.artifacts:
            body.append(f"- `{kind}` — `{path}`")
        body.append("")

    if p.findings:
        body.append("**Findings:**")
        body.append("")
        for f in p.findings:
            body.append(
                f"- [{_SEVERITY_LABELS[f.severity]}] **{f.id}** — {f.title}"
            )
        body.append("")

    return body
